# Generated by Django 5.1.5 on 2025-03-28 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="records",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("speaker", models.TextField(max_length=10)),
                ("content", models.TextField()),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="meetings.meetings",
                    ),
                ),
            ],
        ),
    ]
