# Generated by Django 5.1.5 on 2025-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="profiles",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("sexual_orientation", models.TextField(max_length=50)),
                ("location", models.TextField(max_length=50)),
                ("pronouns", models.CharField(max_length=20)),
                ("education_level", models.CharField(max_length=50)),
                ("occupation", models.CharField(max_length=50)),
                ("political_stand", models.TextField(max_length=100)),
            ],
        ),
    ]
